from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime

def generate_consultation_report(consultation, filename):
    """Generate a PDF report for a consultation"""
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30
    )
    story.append(Paragraph("Medical Consultation Report", title_style))
    story.append(Spacer(1, 12))

    # Patient Information
    story.append(Paragraph("Patient Information", styles["Heading2"]))
    patient_data = [
        ["Age:", str(consultation.age)],
        ["Gender:", consultation.gender],
        ["Date:", consultation.created_at.strftime("%Y-%m-%d %H:%M")]
    ]
    patient_table = Table(patient_data, colWidths=[2*inch, 4*inch])
    patient_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(patient_table)
    story.append(Spacer(1, 12))

    # Symptoms
    story.append(Paragraph("Reported Symptoms", styles["Heading2"]))
    story.append(Paragraph(consultation.symptoms, styles["Normal"]))
    story.append(Spacer(1, 12))

    # Analysis
    story.append(Paragraph("Analysis", styles["Heading2"]))
    story.append(Paragraph(consultation.analysis, styles["Normal"]))
    story.append(Spacer(1, 12))

    # Follow-up Questions
    if consultation.follow_up_questions:
        story.append(Paragraph("Follow-up Discussion", styles["Heading2"]))
        for q in consultation.follow_up_questions:
            story.append(Paragraph(f"Q: {q.question}", styles["Heading4"]))
            story.append(Paragraph(f"A: {q.answer}", styles["Normal"]))
            story.append(Spacer(1, 12))

    # Disclaimer
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey
    )
    story.append(Paragraph(
        "DISCLAIMER: This report is generated by an AI system and is for informational purposes only. "
        "It is not a substitute for professional medical advice, diagnosis, or treatment. "
        "Always seek the advice of your physician or other qualified health provider with any "
        "questions you may have regarding a medical condition.",
        disclaimer_style
    ))

    # Build PDF
    doc.build(story)
    return filename 